language: java

jdk:
  - oraclejdk8

script: mvn verify

after_success:
  - mvn deploy --settings settings.xml

env:
  global:
    secure: EsJt3fc02vImtL1ByH0q1BvBAHrX4OnoPmf2OwflUriob+b98YzutdokBdiYvZLwXJwn3stcxBAFq1BjC0mRkz95ewuekU8hVYCJlFHOFPxp8cjWO8d4v2HqQQNS4bkvMRJeiiPSc3dc9dPlVJ1ad6uWTgohRPMDXP5rLWR0PiZypFIgPOvcNLp5BkuHY+eUsDsTY5O38beONe1bsVxSOhR/8FTxXhRiXDTEqtQsJ2r3ye3QyT0kF3Ar0KuhHlBjpjNUNDz6fHEQ9jktDTqptNbVbbrzmxo4BbGhucsPgUwoHCPIMx1L9KUI3mG4NZR902OQEyQWa8e/rvfZMZyc690O2SO+ifM6Fl5Z1Yu1BUBQg+eueZPRvYWlZOZdYkO2CbYKXXZtC5B3Yy9ODRoZyXwcY8puOlhuUiBMd1UTsazE7I+piHuhcQFVBYPyLD4+WKRp6VyOWLTQT4tkdxfqtemazC8hEU2z+3kVMz/cqTwhEHdYfR5P3GB/gCG3JH7spmrQ+Wia6Ql92+c86dqhYhZY2K4p0aci02boIpNX67zHKBkSKTACHVxUb0DZlWLcMml6t2G6S9YLtZKFlQk6M5HG24ahFCUeqIs4ssjAOz29QV+wHdYQAJqZqrB1Bn00b5CLe3DLMhMdqlGH0M+AUWNfIZrJQLg75j0JzBjuLfc=
